version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'estate-agency'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    networks:
      - estate-agency-network
    volumes:
      - ./data:/data/db

  adminer:
    image: adminer
    ports:
      - 7070:8080
    networks:
      - estate-agency-network

  estate-agency-api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: estate-agency-api
      volumes:
      - ./:/code
      restart: unless-stopped
      environment:
        APP_SETTINGS: ${APP_SETTINGS}
        DATABASE_URL: ${DATABASE_URL}
      ports:
        - 9996:9996
      networks:
        - estate-agency-network
      depends_on:
        - mysql

networks:
  estate-agency-network:
    driver: bridge